
language: php

php:
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
      LARAVEL_VERSION="5.7.*"
    - COMPOSER_FLAGS="--prefer-lowest"
      LARAVEL_VERSION="5.8.*"
    - COMPOSER_FLAGS="--prefer-lowest"
      LARAVEL_VERSION="6.*"
    - COMPOSER_FLAGS=""
      LARAVEL_VERSION="5.7.*"
    - COMPOSER_FLAGS=""
      LARAVEL_VERSION="5.8.*"
    - COMPOSER_FLAGS=""
      LARAVEL_VERSION="6.*"

before_script:
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL_VERSION}" --no-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
script:
  - vendor/bin/phpunit --no-coverage
